import { changeMasterPassword, createVault, generatePassword, saveVault, unlockVault } from "./crypto.js";

const storageGet = (key) => new Promise((resolve) => chrome.storage.local.get(key, resolve));
const storageSet = (value) => new Promise((resolve) => chrome.storage.local.set(value, resolve));
const storageClear = () => new Promise((resolve) => chrome.storage.local.clear(resolve));
const queryTabs = () => new Promise((resolve) => chrome.tabs.query({ active: true, currentWindow: true }, resolve));

const state = { record: null, key: null, vault: null, recoveryKey: null, pendingImport: null };
const screen = document.querySelector("#screen");
let lockTimer;
const esc = (value) => String(value ?? "").replace(/[&<>\"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const showError = (message) => { const node = document.querySelector(".error"); if (node) node.textContent = message; };
const armAutoLock = () => { clearTimeout(lockTimer); lockTimer = setTimeout(() => { state.key = state.vault = null; renderUnlock(); }, 5 * 60 * 1000); };
const markActivity = () => { if (state.vault) armAutoLock(); };
const copyAndClear = async (value) => { try { await navigator.clipboard.writeText(value); setTimeout(async () => { try { if (await navigator.clipboard.readText() === value) await navigator.clipboard.writeText(""); } catch { /* best effort: popup or permission may be unavailable */ } }, 30_000); } catch { showError("无法访问剪贴板，请手动复制"); } };
document.addEventListener("click", markActivity);
document.addEventListener("keydown", markActivity);
document.addEventListener("input", markActivity);

const renderSetup = () => { screen.innerHTML = `<div class="card"><h2>创建你的保险库</h2><div class="notice">主密码不会被保存。请使用你能记住的长密码，并把恢复密钥离线备份好。</div><label>主密码</label><input id="master" type="password" autocomplete="new-password"><label>确认主密码</label><input id="confirm" type="password" autocomplete="new-password"><div class="actions"><button id="create">创建保险库</button><button class="secondary" id="import">导入加密备份</button><input id="backup-file" type="file" accept="application/json" hidden></div><div class="error"></div></div>`; document.querySelector("#create").onclick = async () => { const master = document.querySelector("#master").value; if (master.length < 12) return showError("主密码至少需要 12 个字符"); if (master !== document.querySelector("#confirm").value) return showError("两次输入的主密码不一致"); const created = await createVault(master); state.record = created.record; state.recoveryKey = created.recoveryKey; await storageSet({ vault: state.record }); renderRecovery(); }; document.querySelector("#import").onclick = () => document.querySelector("#backup-file").click(); document.querySelector("#backup-file").onchange = importBackup; };

const renderRecovery = () => { screen.innerHTML = `<div class="card"><h2>备份恢复密钥</h2><div class="notice">这是唯一的恢复入口，只显示一次。请复制到密码管理器或离线纸张保存，不要截图或发送给任何人。</div><div class="recovery">${esc(state.recoveryKey)}</div><div class="actions"><button id="copied">我已安全备份</button></div></div>`; document.querySelector("#copied").onclick = () => renderUnlock(); };

const renderUnlock = () => { screen.innerHTML = `<div class="card"><h2>解锁保险库</h2><label>主密码</label><input id="master" type="password" autocomplete="current-password"><div class="actions"><button id="unlock">解锁</button><button class="secondary" id="recover">用恢复密钥</button></div><div class="actions"><button class="secondary" id="import">导入加密备份</button><input id="backup-file" type="file" accept="application/json" hidden></div><div class="error"></div></div>`; document.querySelector("#unlock").onclick = () => unlock(document.querySelector("#master").value, "master"); document.querySelector("#import").onclick = () => document.querySelector("#backup-file").click(); document.querySelector("#backup-file").onchange = importBackup; document.querySelector("#recover").onclick = () => { screen.innerHTML = `<div class="card"><h2>恢复保险库</h2><label>恢复密钥</label><input id="recovery" autocomplete="off"><label>新主密码</label><input id="master" type="password" autocomplete="new-password"><div class="actions"><button id="reset">验证并重设</button></div><div class="error"></div></div>`; document.querySelector("#reset").onclick = async () => { const next = document.querySelector("#master").value; if (next.length < 12) return showError("主密码至少需要 12 个字符"); try { const rotated = await changeMasterPassword(state.record, document.querySelector("#recovery").value.trim(), next, "recovery"); state.record = rotated.record; state.recoveryKey = rotated.recoveryKey; await storageSet({ vault: state.record }); renderRecovery(); } catch { showError("恢复密钥无效"); } }; }; };

const unlock = async (secret, mode) => { try { const opened = await unlockVault(state.record, secret, mode); state.key = opened.vaultKey; state.vault = opened.vault; if (state.pendingImport) { state.record = state.pendingImport; state.pendingImport = null; await storageSet({ vault: state.record }); } renderVault(); armAutoLock(); } catch { showError("密码不正确或保险库已损坏"); } };

const renderVault = () => { const entries = state.vault.entries.map((entry, index) => `<div class="entry"><div class="entry-info"><div class="entry-title">${esc(entry.name || entry.origin)}</div><div class="entry-meta">${esc(entry.username)} · ${esc(entry.origin)}</div></div><button data-fill="${index}">填充</button><button class="secondary" data-copy="${index}">复制</button></div>`).join("") || `<p class="muted">还没有保存的密码条目。</p>`; screen.innerHTML = `<div class="card"><h2>生成密码</h2><div class="row"><div><label>长度</label><input id="length" type="number" min="8" max="128" value="24"></div><div><label>字符集</label><select id="symbols"><option value="yes">含符号</option><option value="no">无符号</option></select></div></div><input id="generated" readonly value="${generatePassword({ length: 24 })}"><div class="actions"><button id="regen">重新生成</button><button class="secondary" id="copygen">复制</button></div></div><div class="card"><h2>保存密码条目</h2><label>名称</label><input id="name" placeholder="例如：论坛账号"><label>网站 origin</label><input id="origin" placeholder="https://example.com"><label>用户名</label><input id="username" autocomplete="username"><label>密码</label><input id="password" type="password" autocomplete="new-password"><label>备注（可选）</label><textarea id="notes"></textarea><div class="actions"><button id="save">保存条目</button></div><div class="error"></div></div><div class="card"><h2>已保存条目</h2>${entries}<div class="actions"><button class="secondary" id="lock">锁定</button><button class="secondary" id="export">导出备份</button><button class="danger" id="wipe">清空保险库</button></div></div>`; document.querySelector("#regen").onclick = () => { document.querySelector("#generated").value = generatePassword({ length: Number(document.querySelector("#length").value), symbols: document.querySelector("#symbols").value === "yes" }); armAutoLock(); }; document.querySelector("#copygen").onclick = () => copyAndClear(document.querySelector("#generated").value); document.querySelector("#save").onclick = saveEntry; document.querySelector("#lock").onclick = () => { clearTimeout(lockTimer); state.key = state.vault = null; renderUnlock(); }; document.querySelector("#wipe").onclick = async () => { if (confirm("确定清空保险库？此操作不可恢复。")) { await storageClear(); location.reload(); } }; document.querySelector("#export").onclick = exportBackup; document.querySelectorAll("[data-copy]").forEach((button) => button.onclick = () => copyAndClear(state.vault.entries[button.dataset.copy].password)); document.querySelectorAll("[data-fill]").forEach((button) => button.onclick = () => fillEntry(state.vault.entries[button.dataset.fill])); };

const saveEntry = async () => { const rawOrigin = document.querySelector("#origin").value.trim(); try { if (!/^https?:\/\/[^/]+$/.test(rawOrigin)) throw new Error("请输入完整 origin，例如 https://example.com"); const origin = new URL(rawOrigin).origin; const entry = { id: crypto.randomUUID(), name: document.querySelector("#name").value.trim(), origin, username: document.querySelector("#username").value, password: document.querySelector("#password").value, notes: document.querySelector("#notes").value }; if (!entry.password) throw new Error("密码不能为空"); state.vault.entries.push(entry); state.record = await saveVault(state.record, state.key, state.vault); await storageSet({ vault: state.record }); renderVault(); } catch (error) { showError(error.message); } };
const fillEntry = async (entry) => { const [tab] = await queryTabs(); if (!tab?.id || !tab.url) return showError("无法获取当前标签页"); try { if (new URL(tab.url).origin !== entry.origin) throw new Error("当前页面 origin 与条目不匹配"); const [{ result }] = await new Promise((resolve, reject) => chrome.scripting.executeScript({ target: { tabId: tab.id }, func: (payload) => { if (window.location.origin !== payload.origin) return { ok: false, error: "当前网站与条目 origin 不匹配" }; const username = document.querySelector('input[autocomplete="username"], input[type="email"], input[type="text"]'); const password = document.querySelector('input[type="password"]'); if (!password) return { ok: false, error: "没有找到密码输入框" }; const emit = (element, type) => element.dispatchEvent(new Event(type, { bubbles: true })); if (username && payload.username) { username.value = payload.username; emit(username, "input"); emit(username, "change"); } password.value = payload.password; emit(password, "input"); emit(password, "change"); return { ok: true }; }, args: [{ origin: entry.origin, username: entry.username, password: entry.password }] }, (results) => chrome.runtime.lastError ? reject(new Error(chrome.runtime.lastError.message)) : resolve(results))); if (!result?.ok) throw new Error(result?.error || "填充失败"); } catch (error) { showError(error.message); } };
const exportBackup = async () => { const blob = new Blob([JSON.stringify({ format: "strong-vault-backup", vault: state.record }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "strong-vault-backup.json"; anchor.click(); URL.revokeObjectURL(url); };
const importBackup = async (event) => { const file = event.target.files?.[0]; if (!file) return; try { const parsed = JSON.parse(await file.text()); if (parsed.format !== "strong-vault-backup" || parsed.vault?.version !== 1 || !parsed.vault.masterWrap || !parsed.vault.recoveryWrap || !parsed.vault.data) throw new Error("备份文件格式无效"); state.pendingImport = parsed.vault; state.record = parsed.vault; renderUnlock(); } catch (error) { showError(error.message || "无法导入备份"); } };

(async () => { const stored = await storageGet("vault"); if (!stored.vault) renderSetup(); else { state.record = stored.vault; renderUnlock(); } })();
